from __future__ import annotations

API_VERSION = 1
PROFILES = ("quick", "reproduce", "full")

DEFAULT_MAX_BYTES = 5 * 1024**3
DEFAULT_MAX_ENTRIES = 128
DEFAULT_MAX_EVIDENCE_BYTES = 1024**3
DEFAULT_MAX_EVIDENCE_ENTRIES = 512
DEFAULT_MAX_AGE_DAYS = 30
DEFAULT_MAX_VOLUMES = 24
DEFAULT_MAX_VOLUME_BYTES = 3 * 1024**3
DEFAULT_MIN_FREE_BYTES = 2 * 1024**3
AUTOMATIC_PRUNE_INTERVAL_SECONDS = 24 * 60 * 60
RUNNER_CONTROL_TIMEOUT_SECONDS = 15

APPLE_CONTAINER_MIN_VERSION = (1, 0, 0)
